export default {
    REQUEST_SEARCH: 'PAGE/REQUEST_SEARCH',
    SEARCH_REQUEST_FAILED: 'PAGE/SEARCH_REQUEST_FAILED',
    SEARCH_REQUEST_SUCCEEDED: 'PAGE/SEARCH_REQUEST_SUCEEDED',
    SET_RESULTS: 'PAGE/SET_RESULTS',
};
