export default {
    PAGE_RESOLVE_REQUEST_SUCCEEDED: 'APPLICATION/PAGE_RESOLVE_REQUEST_SUCCEEDED',
    PAGE_RESOLVE_REQUEST_FAILED: 'APPLICATION/PAGE_RESOLVE_REQUEST_FAILED',
    REQUEST_PAGE_RESOLVE: 'APPLICATION/REQUEST_PAGE_RESOLVE',
    SET_PAGE_RESOLVE: 'APPLICATION/SET_PAGE_RESOLVE',
    SET_PAGE_COMPONENT: 'APPLICATION/SET_PAGE_COMPONENT',
};
