export default {
    RESOLVE_REQUEST_SUCCEEDED: 'RESOLVE_REQUEST_SUCCEEDED',
    RESOLVE_REQUEST_FAILED: 'RESOLVE_REQUEST_FAILED',
    REQUEST_RESOLVE: 'REQUEST_RESOLVE',
    SET_RESOLVE: 'SET_RESOLVE',
};
